<?php
require_once($_SERVER['DOCUMENT_ROOT'] . '/wp-load.php');

global $wpdb;

$table_name = $wpdb->prefix . "emplyment";

$sql = "CREATE TABLE IF NOT EXISTS $table_name (
  ID INT NOT NULL AUTO_INCREMENT,
  full_name VARCHAR(255) NOT NULL,
  father_name VARCHAR(255) NOT NULL,
  birth_date DATE NOT NULL,
  birth_location VARCHAR(255) NOT NULL,
  nationality VARCHAR(255) NOT NULL,
  soldiership VARCHAR(255) NOT NULL,
  marriage_state VARCHAR(255) NOT NULL,
  number_of_children INT NOT NULL,
  landline_number VARCHAR(255) NOT NULL,
  phone_number VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  zip_code VARCHAR(255) NOT NULL,
  residence_address VARCHAR(255) NOT NULL,
  grade VARCHAR(255) NOT NULL,
  field_of_study VARCHAR(255) NOT NULL,
  city_of_education VARCHAR(255) NOT NULL,
  name_of_school_university VARCHAR(255) NOT NULL,
  from_year VARCHAR(255) NOT NULL,
  to_year VARCHAR(255) NOT NULL,
  job_title VARCHAR(255) NOT NULL,
  workplace_name VARCHAR(255) NOT NULL,
  workplace_number VARCHAR(255) NOT NULL,
  job_start_time VARCHAR(255) NOT NULL,
  job_end_time VARCHAR(255) NOT NULL,
  income VARCHAR(255) NOT NULL,
  reason_of_leaving VARCHAR(255) NOT NULL,
  course_title VARCHAR(255) NOT NULL,
  course_institution VARCHAR(255) NOT NULL,
  city_of_course VARCHAR(255) NOT NULL,
  course_duration VARCHAR(255) NOT NULL,
  course_start_time VARCHAR(255) NOT NULL,
  course_end_time VARCHAR(255) NOT NULL,
  certificate VARCHAR(255) NOT NULL,
  language_title VARCHAR(255) NOT NULL,
  speaking_level VARCHAR(255) NOT NULL,
  reading_level VARCHAR(255) NOT NULL,
  writing_level VARCHAR(255) NOT NULL,
  hearing_level VARCHAR(255) NOT NULL,
  software_title VARCHAR(255) NOT NULL,
  software_level VARCHAR(255) NOT NULL,
  employment_status VARCHAR(255) NOT NULL,
  requested_income VARCHAR(255) NOT NULL,
  employment_start_date VARCHAR(255) NOT NULL,
  insurance_records VARCHAR(255) NOT NULL,
  daily_work_mission VARCHAR(255) NOT NULL,
  overtime VARCHAR(255) NOT NULL,
  judicial_records VARCHAR(255) NOT NULL,
  method_of_familiarity VARCHAR(255) NOT NULL,
  disease_or_allergy VARCHAR(255) NOT NULL,
  relative_name_1 VARCHAR(255) NOT NULL,
  method_of_relative_familiarity_1 VARCHAR(255) NOT NULL,
  relative_job_1 VARCHAR(255) NOT NULL,
  relative_number_1 VARCHAR(255) NOT NULL,
  relative_name_2 VARCHAR(255) NOT NULL,
  method_of_relative_familiarity_2 VARCHAR(255) NOT NULL,
  relative_job_2 VARCHAR(255) NOT NULL,
  relative_number_2 VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);";

$wpdb->query($sql);
?>